<a href="https://colab.research.google.com/github/WONI2/python_study/blob/main/data_manipulation_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
# !pip install pathlib
from pathlib import Path
import os

In [10]:
# 1. 텍스트 파일을 부르기
txt_table = pd.read_table('output.txt')

In [11]:
type(txt_table)

pandas.core.frame.DataFrame

In [12]:
# 2. 엑셀 파일을 불러 객체에 할당해보자.
excel_table = pd.read_excel('Financial Sample.xlsx')
excel_table

Country    Product  Units Sold  Sale Price  Gross Sales  \
0                     Canada  Carretera      1618.5          20      32370.0   
1                    Germany  Carretera      1321.0          20      26420.0   
2                     France  Carretera      2178.0          15      32670.0   
3                    Germany  Carretera       888.0          15      13320.0   
4                     Mexico  Carretera      2470.0          15      37050.0   
5                    Germany  Carretera      1513.0         350     529550.0   
6                    Germany    Montana       921.0          15      13815.0   
7                     Canada    Montana      2518.0          12      30216.0   
8                     France    Montana      1899.0          20      37980.0   
9                    Germany    Montana      1545.0          12      18540.0   
10                    Mexico    Montana      2470.0          15      37050.0   
11                    Canada    Montana      2665.5         125     333187.5   
12                    Mexico    Montana       958.0         300     287400.0   
13                   Germany    Montana      2146.0           7      15022.0   
14                    Canada    Montana       345.0         125      43125.0   
15  United States of America    Montana       615.0          15       9225.0   
16                    Canada      Paseo       292.0          20       5840.0   
17                    Mexico      Paseo       974.0          15      14610.0   
18                    Canada      Paseo      2518.0          12      30216.0   

       Sales    COGS    Profit  Month Number Month Name  Year  
0    32370.0   16185   16185.0             1    January  2014  
1    26420.0   13210   13210.0             1    January  2014  
2    32670.0   21780   10890.0             6       June  2014  
3    13320.0    8880    4440.0             6       June  2014  
4    37050.0   24700   12350.0             6       June  2014  
5   529550.0  393380  136170.0            12   December  2014  
6    13815.0    9210    4605.0             3      March  2014  
7    30216.0    7554   22662.0             6       June  2014  
8    37980.0   18990   18990.0             6       June  2014  
9    18540.0    4635   13905.0             6       June  2014  
10   37050.0   24700   12350.0             6       June  2014  
11  333187.5  319860   13327.5             7       July  2014  
12  287400.0  239500   47900.0             8     August  2014  
13   15022.0   10730    4292.0             9  September  2014  
14   43125.0   41400    1725.0            10    October  2013  
15    9225.0    6150    3075.0            12   December  2014  
16    5840.0    2920    2920.0             2   February  2014  
17   14610.0    9740    4870.0             2   February  2014  
18   30216.0    7554   22662.0             6       June  2014

In [13]:
# 5. Row/Column Naming
sr1 = pd.Series([1,2,3,4])
sr1.index = ['a', 'b', 'c', 'd']
sr1

a    1
b    2
c    3
d    4
dtype: int64

In [14]:
df1 = pd.DataFrame(np.arange(10).reshape(5,2))
df1.index = list('abcde')
df1.columns = ['A', 'B']
df1

A  B
a  0  1
b  2  3
c  4  5
d  6  7
e  8  9

In [15]:
# 6. Indexing
sr1.iloc[1:3]

b    2
c    3
dtype: int64

In [16]:
sr1.loc[['b', 'c']]

b    2
c    3
dtype: int64

In [17]:
df1.iloc[3, 0:2]

A    6
B    7
Name: d, dtype: int64

In [18]:
df1.loc[:]['B']

a    1
b    3
c    5
d    7
e    9
Name: B, dtype: int64

In [19]:
# 본격적으로 벡터의 부분집합(서브셋)을 만들어보자.
# 7. Subsetting for vectors

v0 = pd.Series([1, 2, 3, 4, 5, 6])
# Single Element
print(v0[0]); print(v0[1])

1
2


In [20]:
# Multiple Elements
v0[[1, 3, 5]]

1    2
3    4
5    6
dtype: int64

In [21]:
# Logical Sequence Elements
larger_2 = v0 > 2
larger_2

0    False
1    False
2     True
3     True
4     True
5     True
dtype: bool

In [22]:
# 데이터 프레임의 부분집합을 만들어보자.
# 8.Subsetting for data.frame
df1 = pd.DataFrame({'mid' : [100, 92, 93],
                    'final' : [93, 94, 95]})
df1.shape

(3, 2)

In [23]:
df1.iloc[1, 0]

92

In [24]:
df1.iloc[1, 1]

94

In [25]:
type(df1.iloc[1, 0])

numpy.int64

In [26]:
df1.iloc[2, :]

mid      93
final    95
Name: 2, dtype: int64

In [27]:
df1.iloc[:, 1]

0    93
1    94
2    95
Name: final, dtype: int64

In [28]:
# 리스트도 부분집합을 만들어보자.
# 9. Subsetting for Lists
ls2 = [[1, 2, 3], np.arange(1,10).reshape(3,3)]
ls2

[[1, 2, 3],
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])]

In [29]:
# 합쳐보자.
# 10. Merging
# 10.1. Concatenate
ma = np.arange(1, 7).reshape(2, 3)
mb = np.arange(7, 13).reshape(2, 3)
print(ma, '\n', mb)

[[1 2 3]
 [4 5 6]] 
 [[ 7  8  9]
 [10 11 12]]


In [30]:
ma_nrow, ma_ncol = ma.shape
print(ma_nrow, ma_ncol)

2 3


In [4]:
## Join을 배워보자.

##### Join
df1 = pd.DataFrame({'CustomerId' : range(1, 11),
     'Menu' : ("Kimbab " * 3 + "Bibimbab " * 3 + "Odeng " * 4).split()})
df1

CustomerId      Menu
0           1    Kimbab
1           2    Kimbab
2           3    Kimbab
3           4  Bibimbab
4           5  Bibimbab
5           6  Bibimbab
6           7     Odeng
7           8     Odeng
8           9     Odeng
9          10     Odeng

In [6]:
df2 = pd.DataFrame({'CustomerId' : [2, 4, 6],
     'Table' : ("SectorA " * 2 + "SectorB").split()})
df2

CustomerId    Table
0           2  SectorA
1           4  SectorA
2           6  SectorB

In [7]:
df3 = pd.DataFrame({'CustomerId' : [2, 5], 'Gender' : ["Male", "Female"]})
df3

CustomerId  Gender
0           2    Male
1           5  Female

In [8]:
## Inner Join
InnerJoined = pd.merge(df1, df2, on = "CustomerId")
InnerJoined

CustomerId      Menu    Table
0           2    Kimbab  SectorA
1           4  Bibimbab  SectorA
2           6  Bibimbab  SectorB

In [9]:
## Left Outer Join
LeftOuterJoined = pd.merge(df1, df2, on="CustomerId", how='left')
LeftOuterJoined

CustomerId      Menu    Table
0           1    Kimbab      NaN
1           2    Kimbab  SectorA
2           3    Kimbab      NaN
3           4  Bibimbab  SectorA
4           5  Bibimbab      NaN
5           6  Bibimbab  SectorB
6           7     Odeng      NaN
7           8     Odeng      NaN
8           9     Odeng      NaN
9          10     Odeng      NaN

In [10]:
## Right Outer Join
RightOuterJoined = pd.merge(df1, df2, on = "CustomerId", how = 'right')
RightOuterJoined

CustomerId      Menu    Table
0           2    Kimbab  SectorA
1           4  Bibimbab  SectorA
2           6  Bibimbab  SectorB

In [11]:
## Outer Join
OuterJoined = pd.merge(df1, df2, on = "CustomerId", how = 'outer')
OuterJoined

CustomerId      Menu    Table
0           1    Kimbab      NaN
1           2    Kimbab  SectorA
2           3    Kimbab      NaN
3           4  Bibimbab  SectorA
4           5  Bibimbab      NaN
5           6  Bibimbab  SectorB
6           7     Odeng      NaN
7           8     Odeng      NaN
8           9     Odeng      NaN
9          10     Odeng      NaN