<a href="https://colab.research.google.com/github/WONI2/python_study/blob/PYTHON_BASIC/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np_vector = np.array([1,2,3,4], dtype = np.int)
print(np_vector)

[np_vector.shape, np_vector.size, np_vector.dtype, np_vector.ndim]

[1 2 3 4]


<ipython-input-7-837eeb30d98c>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np_vector = np.array([1,2,3,4], dtype = np.int)


[(4,), 4, dtype('int64'), 1]

In [ ]:
np_matrix = np.array([[1,2,3,4],
                     [5,6,7,8],
                     [9,10,11,12]], dtype= np.int)
print(np_matrix)                     

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


<ipython-input-14-d4d3eb2a585b>:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  [9,10,11,12]], dtype= np.int)


In [ ]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.arange(0,9,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.eye(N=3,M=5,k=0)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
np.ones_like(np_matrix)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np_matrix[1,2] = 100

In [ ]:
np_matrix

array([[  1,   2,   3,   4],
       [  5,   6, 100,   8],
       [  9,  10,  11,  12]])

In [ ]:
Z=np.arange(1,46).reshape(5,9)
Z

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45]])

In [ ]:
Y=Z.copy()
Y

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45]])

In [ ]:
Y[:2,:2]

array([[ 1,  2],
       [10, 11]])

In [ ]:
Y[1,1]

11

In [ ]:
Y[:,0]

array([ 1, 10, 19, 28, 37])

In [ ]:
Y[:,0]=1

In [ ]:
Y

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1, 11, 12, 13, 14, 15, 16, 17, 18],
       [ 1, 20, 21, 22, 23, 24, 25, 26, 27],
       [ 1, 29, 30, 31, 32, 33, 34, 35, 36],
       [ 1, 38, 39, 40, 41, 42, 43, 44, 45]])

In [ ]:
Y[0,:]=1

In [ ]:
Y

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1, 11, 12, 13, 14, 15, 16, 17, 18],
       [ 1, 20, 21, 22, 23, 24, 25, 26, 27],
       [ 1, 29, 30, 31, 32, 33, 34, 35, 36],
       [ 1, 38, 39, 40, 41, 42, 43, 44, 45]])

In [ ]:
Y[:,::2]=1

In [ ]:
Y

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1, 11,  1, 13,  1, 15,  1, 17,  1],
       [ 1, 20,  1, 22,  1, 24,  1, 26,  1],
       [ 1, 29,  1, 31,  1, 33,  1, 35,  1],
       [ 1, 38,  1, 40,  1, 42,  1, 44,  1]])

In [ ]:
Y[:-2,:-2]=2

In [ ]:
Y

array([[ 2,  2,  2,  2,  2,  2,  2,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2, 17,  1],
       [ 2,  2,  2,  2,  2,  2,  2, 26,  1],
       [ 1, 29,  1, 31,  1, 33,  1, 35,  1],
       [ 1, 38,  1, 40,  1, 42,  1, 44,  1]])

In [ ]:
Y[2:4,2:4]=3
Y

array([[ 2,  2,  2,  2,  2,  2,  2,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2, 17,  1],
       [ 2,  2,  3,  3,  2,  2,  2, 26,  1],
       [ 1, 29,  3,  3,  1, 33,  1, 35,  1],
       [ 1, 38,  1, 40,  1, 42,  1, 44,  1]])

In [ ]:
Y[::2,::2]=4
Y

array([[ 4,  2,  4,  2,  4,  2,  4,  1,  4],
       [ 2,  2,  2,  2,  2,  2,  2, 17,  1],
       [ 4,  2,  4,  3,  4,  2,  4, 26,  4],
       [ 1, 29,  3,  3,  1, 33,  1, 35,  1],
       [ 4, 38,  4, 40,  4, 42,  4, 44,  4]])

In [ ]:
Y[3::2,3::2]=5
Y

array([[ 4,  2,  4,  2,  4,  2,  4,  1,  4],
       [ 2,  2,  2,  2,  2,  2,  2, 17,  1],
       [ 4,  2,  4,  3,  4,  2,  4, 26,  4],
       [ 1, 29,  3,  5,  1,  5,  1,  5,  1],
       [ 4, 38,  4, 40,  4, 42,  4, 44,  4]])

In [ ]:
A = Z.copy()
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45]])

In [ ]:
A[::2,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [37, 38, 39, 40, 41, 42, 43, 44, 45]])

In [ ]:
A[:-2,:-2]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15, 16],
       [19, 20, 21, 22, 23, 24, 25]])

In [ ]:
A[:-2,-2:]

array([[ 8,  9],
       [17, 18],
       [26, 27]])

In [ ]:
A[-2:,-2:]

array([[35, 36],
       [44, 45]])

In [ ]:
A[-3:,-3:]

array([[25, 26, 27],
       [34, 35, 36],
       [43, 44, 45]])

In [ ]:
A[-5:,-5:]

array([[ 5,  6,  7,  8,  9],
       [14, 15, 16, 17, 18],
       [23, 24, 25, 26, 27],
       [32, 33, 34, 35, 36],
       [41, 42, 43, 44, 45]])

In [ ]:
np_vector = np.arange(1,13,dtype = int)

In [ ]:
np_vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np_vector<9


array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False])

In [ ]:
np_vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np_matrix = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]], dtype = np.int)
np_matrix

<ipython-input-48-d556d9fb3368>:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  [9, 10, 11, 12]], dtype = np.int)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np_matrix[[1, 2, 1], 
          [0, 2, 3]]

array([ 5, 11,  8])

In [ ]:
print(np_vector.sum())
print(np.sum(np_vector))

78
78


In [ ]:
np_vector_1 = np.arange(1,13,dtype = int)
np_vector_2 = np.arange(13,25,dtype = int)


In [ ]:
np_vector_1 + np_vector_2
# 각 배열의 같은자리의 숫자끼리의 합

array([14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36])

In [ ]:
sum(np_vector_1*np_vector_2) 
# 배열 내의 총 합을 구하는 것 

1586

In [ ]:
np.concatenate((np_vector_1,np_vector_2))
# 배열을 붙여넣어주는 것

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
np_matrix_1 = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]], dtype = int)
np_matrix_2 = np.arange(13,25,dtype= int).reshape(3,4)
# 3x4행렬로 reshape 해준 것

In [ ]:
np_matrix_1 * np_matrix_2
# 행렬에 각 자리수끼리의 곱을 나타냄. 기존의 행렬의 계산과 좀 다른 것 같은데 

array([[ 13,  28,  45,  64],
       [ 85, 108, 133, 160],
       [189, 220, 253, 288]])

In [ ]:
np_matrix_2.T
# transpose가 뭔지에 대해서 다시 한번 공부해보기
#dot에 대해서도 다시한번

array([[13, 17, 21],
       [14, 18, 22],
       [15, 19, 23],
       [16, 20, 24]])

In [ ]:
np_scalar_1 = int(3)
np_vector_3 = np.array([1,2,3,4],dtype =int)
np_vector_4 = np.array([1,2,3], dtype=int)

print(f'np_matrix_1: \n {np_matrix_1}\n')
print(f'np_scalar_1: \n {np_scalar_1}\n')
print(f'np_vector_3: \n {np_vector_3}\n')
print(f'np_vector_4: \n {np_vector_4}\n')

np_matrix_1: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

np_scalar_1: 
 3

np_vector_3: 
 [1 2 3 4]

np_vector_4: 
 [1 2 3]



In [ ]:
np_matrix_1 + np_scalar_1


array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np_matrix_1 + np_vector_4.reshape(3, 1)

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [ ]:
np.where(np_vector_3 > 2)
# 조건이 있는 자리가 어디에 있는지 물어보는 것.

(array([2, 3]),)

In [ ]:
np.argmax(np_vector_3)
# np_vector_3의 가장 큰 수가 있는 index를 보여 줌.

3

In [ ]:
np.argmax(np_matrix_1, axis=0)

array([2, 2, 2, 2])

In [ ]:
np.nan


nan

In [ ]:
np.inf

inf

In [ ]:
a= pd.Series([1,2,3,4], index = ['a','b','c','d'])
a


a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
sr1 = pd.Series(np.arange(1,13, dtype = int))
sr1
# 인덱스를 정해주지 않으면 정수로 0부터 작성해줌 

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
dtype: int64

In [ ]:
sr1 = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd'])
sr2 = pd.Series([5, 6, 7, 8, 9], index = ['a', 'b', 'c', 'd', 'e'])

In [ ]:
sr1 + sr2
# NaN값을 처리하기 쉬운 형태로 반환해준 것.

a     6.0
b     8.0
c    10.0
d    12.0
e     NaN
dtype: float64